steps:
- name: node:10.13.0
  entrypoint: yarn
  args: ['install']
- name: node:10.13.0
  entrypoint: yarn
  args: ['run', 'build']
# - name: 'ubuntu'
#   args: ['bash', './prep.sh']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]

timeout: "1600s"
